[project]
name = "royal-tactician"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index>=0.13.1",
    "streamlit>=1.48.0",
    "watchdog>=6.0.0",
]
